nacos:
  config:
    server-addr: 127.0.0.1:8848

spring:
  application:
    name: gym-service-member

server:
  port: 8082

dubbo:
  application:
    name: gym-service-member
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: 20882
  scan:
    base-packages: com.v1.service.member.provider
