#端口号配置
server:
  port: 9999

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 500MB

#mybatis plus配置（全局配置仅web模块需要）
mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty

# 定义日志文件的输出格式
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'


#jwt配置
jwt:
  issuer: gaobie
  secret: com.v1
  expiration: 30

# Dubbo Consumer 配置
dubbo:
  application:
    name: gym-service-web
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
    timeout: 10000

#不需要token验证的请求
ignore:
  url: /api/login/login,/api/login/image,/swagger-ui.html,/swagger-resources,/webjars,/v2/api-docs
